export const checkboxes = [
  {
    name: 'drama',
    key: 'drama',
    isChecked: false,
    label: 'Drama',
  },
  {
    name: 'action',
    key: 'action',
    isChecked: false,
    label: 'Action',
  },
  {
    name: 'comedy',
    key: 'comedy',
    isChecked: false,
    label: 'Comedy',
  },
  {
    name: 'crime',
    key: 'crime',
    isChecked: false,
    label: 'Crime',
  },
  // {
  //   name: 'western',
  //   key: 'western',
  //   isChecked: false,
  //   label: 'Western',
  // },
  // {
  //   name: 'family',
  //   key: 'family',
  //   isChecked: false,
  //   label: 'Family',
  // },
  // {
  //   name: 'documentary',
  //   key: 'documentary',
  //   isChecked: false,
  //   label: 'Documentary',
  // },
  // {
  //   name: 'thriller',
  //   key: 'thriller',
  //   isChecked: false,
  //   label: 'Thriller',
  // },
  // {
  //   name: 'mystery',
  //   key: 'mystery',
  //   isChecked: false,
  //   label: 'Mystery',
  // },
  // {
  //   name: 'war',
  //   key: 'war',
  //   isChecked: false,
  //   label: 'War',
  // },
  // {
  //   name: 'fantasy',
  //   key: 'fantasy',
  //   isChecked: false,
  //   label: 'Fantasy',
  // },
  // {
  //   name: 'romance',
  //   key: 'romance',
  //   isChecked: false,
  //   label: 'Romance',
  // },
  // {
  //   name: 'adventure',
  //   key: 'adventure',
  //   isChecked: false,
  //   label: 'Adventure',
  // },
  // {
  //   name: 'animation',
  //   key: 'animation',
  //   isChecked: false,
  //   label: 'Animation',
  // },
  // {
  //   name: 'horror',
  //   key: 'horror',
  //   isChecked: false,
  //   label: 'Horror',
  // },
  // {
  //   name: 'history',
  //   key: 'history',
  //   isChecked: false,
  //   label: 'History',
  // },
  // {
  //   name: 'science fiction',
  //   key: 'science fiction',
  //   isChecked: false,
  //   label: 'Science Fiction',
  // },
  // {
  //   name: 'music',
  //   key: 'music',
  //   isChecked: false,
  //   label: 'Music',
  // },
];
