export const genreObjList = [
  { lang: 'English', code: 'en' },
  { lang: 'Chinese', code: 'zh' },
  { lang: 'French', code: 'fr' },
  { lang: 'Spanish', code: 'es' },
  { lang: 'German', code: 'de' },
  { lang: 'Russian', code: 'ru' },
  { lang: 'Hebrew', code: 'he' },
  { lang: 'Swedish', code: 'sv' },
  { lang: 'Portugese', code: 'pt' },
  { lang: 'Italian', code: 'it' },
  { lang: 'Japanese', code: 'ja' },
  { lang: 'Korean', code: 'ko' },
  { lang: 'Hindi', code: 'hi' },
  { lang: 'Hungary', code: 'hu' },
];
